# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Cristian Bastidas
# email: 
  
description: >- # this means to ignore newlines until "baseurl:"
  Ciencias de la computación. Tutoriales y experiencias personales.
# Blog about computer science. You will learn with tutorials, personal experiences, and code.

baseurl: "/my-blog" # the subpath of your site, e.g. /blog
url: "https://crixodia.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Removed due to new minima version
# twitter_username: crixodia
# github_username:  crixodia

# 50px Height is the best option
# title-logo: /images/title-logo.png

disqus:
  shortname: crixodiablog-1

minima:
  skin: dark
  social_links:
      twitter: crixodia
      github: crixodia
      stackoverflow: "8524034"
      instagram: crixodia
      linkedin: crixodia
      youtube_channel: UCIIszmFMvyNn5gj0xwrxIsg
      youtube_channel_name: Gabriel Bastidas

author:
  name: Cristian G. Bastidas
#  email: "gabrielbastidas5g@outlook.com"

message: "Made with ❤ by Crixodia"
#copyright:

google_analytics: G-EKGGQ4L26M

# Build settings
# Removed to use general theme
# theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# How to post
# filename: 2021-03-18-welcome-to-jekyll.markdown
# ---
# layout: post
# title:  "Welcome to Jekyll!"
# date:   2021-03-18 02:04:19 -0500
# categories: jekyll update
# language: es
# image: /assets/images/default-featured-image.jpg
# ---